# Generated by Django 3.2.6 on 2021-08-08 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onenightwerewolf', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TodoModel',
            new_name='NameModel',
        ),
    ]
