# Generated by Django 3.2.6 on 2021-08-09 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onenightwerewolf', '0002_rename_todomodel_amongusmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('villager', models.IntegerField(blank=True, default=0, null=True)),
                ('fortune_teller', models.IntegerField(blank=True, default=0, null=True)),
                ('thief', models.IntegerField(blank=True, default=0, null=True)),
                ('werewolf', models.IntegerField(blank=True, default=0, null=True)),
                ('madman', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='namemodel',
            name='memo',
        ),
        migrations.RemoveField(
            model_name='namemodel',
            name='title',
        ),
        migrations.AddField(
            model_name='namemodel',
            name='name',
            field=models.CharField(default='a', max_length=50),
        ),
    ]
