# Generated by Django 3.2.6 on 2021-08-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onenightwerewolf', '0003_auto_20210809_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namemodel',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
