# Generated by Django 3.2.6 on 2021-08-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onenightwerewolf', '0004_alter_namemodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='namemodel',
            name='username',
            field=models.CharField(default='a', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='numbermodel',
            name='username',
            field=models.CharField(default='a', max_length=50),
            preserve_default=False,
        ),
    ]
