# Generated by Django 3.2.6 on 2021-08-22 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onenightwerewolf', '0005_auto_20210809_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namemodel',
            name='username',
            field=models.CharField(blank=True, default='bambook', max_length=50, null=True),
        ),
    ]
