# Generated by Django 3.2.4 on 2021-10-15 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onenightwerewolf', '0006_alter_namemodel_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namemodel',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
